import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import NextAuthProvider from "../components/NextAuthProvider/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/authOptions";
import ConditionalLayout from "../components/ConditionalLayout/ConditionalLayout";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const session = await getServerSession(authOptions);
console.log(session);
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NextAuthProvider>
          <ConditionalLayout>{children}</ConditionalLayout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
