import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "../components/NextAuthProvider/NextAuthProvider";
import ConditionalLayout from "../components/ConditionalLayout/ConditionalLayout";
import { cn } from "@/lib/utils";
import NextThemeProvider from "../components/NextThemeProvider/NextThemeProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        inter.className,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full  flex flex-col">
        <NextAuthProvider>
          <NextThemeProvider>
            <ConditionalLayout>{children}</ConditionalLayout>
          </NextThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
